# -*- coding: utf-8 -*-
"""LORA-FINE-TUNING.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13TH4kOG9VMFHe1fAnGG6_00pr_t2_X-t
"""

!pip install datasets transformers accelerate tokenizers

from transformers import GPT2LMHeadModel, GPT2Tokenizer,Trainer, TrainingArguments

from datasets import load_dataset

datasets=load_dataset("text",data_files="/content/dr_patient.txt")

datasets

tokenizer=GPT2Tokenizer.from_pretrained("gpt2")

tokenizer.pad_token=tokenizer.eos_token

model=GPT2LMHeadModel.from_pretrained("gpt2")

def tokenize_function(examples):
  tokenizer_inputs=tokenizer(examples["text"],truncation=True,padding="max_length",max_length=128)
  tokenizer_inputs["labels"]=tokenizer_inputs["input_ids"].copy()
  return tokenizer_inputs

tokenized_dataset=datasets.map(tokenize_function,batched=True,num_proc=4,remove_columns=["text"])

tokenized_dataset

from peft import get_peft_model,LoraConfig,TaskType

lora_config=LoraConfig(
    r=8,
    lora_alpha=64,
    target_modules=["c_attn"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

peft_model=get_peft_model(model,lora_config)

peft_model.print_trainable_parameters()

training_args=TrainingArguments(
    output_dir="./Lora_dr_patient_finetuned",
    overwrite_output_dir=True,
    num_train_epochs=5,
    per_device_train_batch_size=4,
    save_steps=500,
    save_total_limit=2
)

trainer=Trainer(
    model=peft_model,
    args=training_args,
    train_dataset=tokenized_dataset["train"]
)

trainer.train()

model.save_pretrained("./Lora_dr_patient_finetuned")

input_prompt="Doctor : I have headache"

from transformers import pipeline

generator=pipeline("text-generation",model="./Lora_dr_patient_finetuned",tokenizer=tokenizer)


result=generator(input_prompt,max_length=100,do_sample=True)
print(result[0]["generated_text"])





